### ISSUE TITLE
[Update Template] Submit button remains disabled

### ISSUE THREAD

**Issue by chuayk** [MattRuddick/aws-ses-template-manager#3]
When attempting to update an existing template.
The submit button of the page does not switch itself to enabled even after modifying the fields.

The workaround I have used so far is to remove the `disabled` attribute from `template-form.edge` or directly remove via browser inspector.

**Comment by MattRuddick** [comment]
Thanks for bringing this one up! I found that the submit button would change to enabled only when the input value has been changed **and** we focus/click away from the input itself. This wasn't great UX as I would change a value in a single input and normally expect to be able to submit but wouldn't be allowed to.

I since changed the type of event listener (bound to all the inputs) so now that any changes to any of the inputs will allow that submit button to become active.

I thought keeping the disabled attribute in by default (no form input changes) was good to ensure the user can't just update a template without any changes or attempt to create a new one with all blank values.

Changes applied and released as part of v1.5.4
